### ISSUE TITLE
Is it possible to set FK reference for table which has been defined below?

### ISSUE THREAD

**Issue by pasxel** [ComPHPPuebla/dbal-fixtures#8]
Is it possible to set FK reference for table which has been defined below?
For example:
```
comments:
    comment_1:
        user: '@user_1'

users:
    user_1:
        last_comment: '@comment_1'
```

I see 'INSERT' like:
`INSERT INTO comments (user) VALUES (?)' with params ["@user_1"]`

**Comment by MontealegreLuis** [comment]
Hi @pasxel 

No that's not possible if the primary key for both `comments` and `users` is generated automatically, for instance: with `AUTO_INCREMENT`.
It produces a *circular dependency*. In order to run the insert for `comments`, we need to run the one for `users` first, but the `users` insert is expecting the `comments` insert to be run first as well.

In order to insert `comment_1` we'd need the ID of `user_1` which hasn't been generated yet. 
If we try to insert in the opposite order, we would have a similar problem. 
In order to insert `user_1` we need to know the ID of `comment_1`, but we can't because that insert hasn't run yet.

It would be possible if both of your table's primary keys are not generated automatically, and you set them directly in the `yml` file. For instance:

```yml
comments:
    comment_1:
        id: 1                       
        user: 1 # This refers to @user_1

users:
    user_1:
        id: 1
        last_comment: 1 # this refers to @comment_1
```
